#!/usr/bin/env bash

g++     -std=c++14 -v \
        -g -Wl,--subsystem,windows \
        -IC:/Users/darko/source/SDL2/include \
        -LC:/Users/darko/source/SDL2/lib \
        -O3 \
        -lSDL2 \
        -lSDL2_image \
        -lSDL2_mixer \
        -lSDL2_ttf \
        -obin/mousetrap.exe \
        src/entities.cc \
        src/entity.cc \
        src/systems.cc \
        src/game.cc \
        src/main.cc 

# g++     -std=c++14 -v \
#         -g -Wl,--subsystem,windows \
#         -IC:/Users/darko/source/SDL2/include \
#         -LC:/Users/darko/source/SDL2/lib \
#         -O3 \
#         -lSDL2 \
#         -lSDL2_image \
#         -lSDL2_mixer \
#         -lSDL2_ttf \
#         -obin/mousetrap.exe \
#         cpp/entities.cc \
#         cpp/systems.cc \
#         cpp/game.cc \
#         cpp/main.cc 

