/* demo.c generated by valac 0.34.7, the Vala compiler
 * generated from demo.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL.h>
#include <stdlib.h>
#include <string.h>
#include <emscripten.h>

#define _SDL_FreeSurface0(var) ((var == NULL) ? NULL : (var = (SDL_FreeSurface (var), NULL)))


extern SDL_Surface* surface;
SDL_Surface* surface = NULL;
extern SDL_Surface* bgd;
SDL_Surface* bgd = NULL;

void _vala_main (gchar** args, int args_length1);
void main_loop (void* game);
static void _main_loop_em_arg_callback_func (void* arg);


static void _main_loop_em_arg_callback_func (void* arg) {
	main_loop (arg);
}


void _vala_main (gchar** args, int args_length1) {
	gint _tmp0_ = 0;
	SDL_Surface* _tmp2_ = NULL;
	SDL_Surface* _tmp3_ = NULL;
	SDL_Surface* _tmp5_ = NULL;
	SDL_Surface* _tmp6_ = NULL;
	_tmp0_ = SDL_Init ((guint32) SDL_INIT_VIDEO);
	if (_tmp0_ < 0) {
		const gchar* _tmp1_ = NULL;
		_tmp1_ = SDL_GetError ();
		g_print ("Unable to init SDL %s\n", _tmp1_);
		return;
	}
	_tmp2_ = SDL_SetVideoMode (800, 300, 32, (guint32) (SDL_HWSURFACE | SDL_DOUBLEBUF));
	surface = _tmp2_;
	_tmp3_ = surface;
	if (_tmp3_ == NULL) {
		const gchar* _tmp4_ = NULL;
		_tmp4_ = SDL_GetError ();
		g_print ("Unable to set video %s\n", _tmp4_);
		return;
	}
	_tmp5_ = SDL_LoadBMP ("assets/images/background.png");
	_SDL_FreeSurface0 (bgd);
	bgd = _tmp5_;
	_tmp6_ = bgd;
	if (_tmp6_ == NULL) {
		const gchar* _tmp7_ = NULL;
		_tmp7_ = SDL_GetError ();
		g_print ("Unable to load bpm %s\n", _tmp7_);
		return;
	}
	SDL_WM_SetCaption ("ShmupWarz", "ShmupWarz");
	emscripten_set_main_loop_arg (_main_loop_em_arg_callback_func, NULL, 0, 1);
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	_vala_main (argv, argc);
	return 0;
}


void main_loop (void* game) {
	SDL_Event event = {0};
	while (TRUE) {
		SDL_Event _tmp0_ = {0};
		gint _tmp1_ = 0;
		SDL_Event _tmp2_ = {0};
		guchar _tmp3_ = '\0';
		SDL_Surface* _tmp4_ = NULL;
		SDL_Surface* _tmp5_ = NULL;
		SDL_PixelFormat* _tmp6_ = NULL;
		guint32 _tmp7_ = 0U;
		SDL_Surface* _tmp8_ = NULL;
		SDL_Surface* _tmp9_ = NULL;
		SDL_Surface* _tmp10_ = NULL;
		_tmp1_ = SDL_PollEvent (&_tmp0_);
		event = _tmp0_;
		if (!(_tmp1_ > 0)) {
			break;
		}
		_tmp2_ = event;
		_tmp3_ = _tmp2_.type;
		switch (_tmp3_) {
			case SDL_QUIT:
			{
				{
				}
				break;
			}
			default:
			break;
		}
		_tmp4_ = surface;
		_tmp5_ = surface;
		_tmp6_ = _tmp5_->format;
		_tmp7_ = SDL_MapRGB (_tmp6_, (guchar) 255, (guchar) 0, (guchar) 0);
		SDL_FillRect (_tmp4_, NULL, _tmp7_);
		_tmp8_ = bgd;
		_tmp9_ = surface;
		SDL_UpperBlit (_tmp8_, NULL, _tmp9_, NULL);
		_tmp10_ = surface;
		SDL_Flip (_tmp10_);
	}
}



