/* game.c generated by valac 0.34.7, the Vala compiler
 * generated from game.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <float.h>
#include <math.h>
#include <SDL.h>
#include <stdlib.h>
#include <string.h>
#include <emscripten.h>

typedef struct _Game Game;

#define ENTITAS_TYPE_ENTITY (entitas_entity_get_type ())

#define ENTITAS_TYPE_BACKGROUND (entitas_background_get_type ())
typedef struct _entitasBackground entitasBackground;

#define ENTITAS_TYPE_BOUNDS (entitas_bounds_get_type ())
typedef struct _entitasBounds entitasBounds;

#define ENTITAS_TYPE_BULLET (entitas_bullet_get_type ())
typedef struct _entitasBullet entitasBullet;

#define ENTITAS_TYPE_ENEMY1 (entitas_enemy1_get_type ())
typedef struct _entitasEnemy1 entitasEnemy1;

#define ENTITAS_TYPE_ENEMY2 (entitas_enemy2_get_type ())
typedef struct _entitasEnemy2 entitasEnemy2;

#define ENTITAS_TYPE_ENEMY3 (entitas_enemy3_get_type ())
typedef struct _entitasEnemy3 entitasEnemy3;

#define ENTITAS_TYPE_EXPIRES (entitas_expires_get_type ())
typedef struct _entitasExpires entitasExpires;

#define ENTITAS_TYPE_HEALTH (entitas_health_get_type ())
typedef struct _entitasHealth entitasHealth;

#define ENTITAS_TYPE_HUD (entitas_hud_get_type ())
typedef struct _entitasHud entitasHud;

#define ENTITAS_TYPE_INDEX (entitas_index_get_type ())
typedef struct _entitasIndex entitasIndex;

#define ENTITAS_TYPE_LAYER (entitas_layer_get_type ())
typedef struct _entitasLayer entitasLayer;

#define ENTITAS_TYPE_POSITION (entitas_position_get_type ())
typedef struct _entitasPosition entitasPosition;

#define ENTITAS_TYPE_SCALE (entitas_scale_get_type ())
typedef struct _entitasScale entitasScale;

#define ENTITAS_TYPE_SPRITE (entitas_sprite_get_type ())
typedef struct _entitasSprite entitasSprite;

#define ENTITAS_TYPE_TEXT (entitas_text_get_type ())
typedef struct _entitasText entitasText;

#define ENTITAS_TYPE_TINT (entitas_tint_get_type ())
typedef struct _entitasTint entitasTint;

#define ENTITAS_TYPE_TWEEN (entitas_tween_get_type ())
typedef struct _entitasTween entitasTween;

#define ENTITAS_TYPE_VELOCITY (entitas_velocity_get_type ())
typedef struct _entitasVelocity entitasVelocity;
typedef struct _entitasEntity entitasEntity;
typedef struct _Factory Factory;
#define _factory_free0(var) ((var == NULL) ? NULL : (var = (factory_free (var), NULL)))
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))

#define TYPE_POOL (pool_get_type ())
#define _g_free0(var) (var = (g_free (var), NULL))

struct _entitasBackground {
	gboolean active;
};

struct _entitasBounds {
	gint x;
	gint y;
	gint w;
	gint h;
};

struct _entitasBullet {
	gboolean active;
};

struct _entitasEnemy1 {
	gboolean active;
};

struct _entitasEnemy2 {
	gboolean active;
};

struct _entitasEnemy3 {
	gboolean active;
};

struct _entitasExpires {
	gdouble value;
};

struct _entitasHealth {
	gdouble current;
	gdouble maximum;
};

struct _entitasHud {
	gboolean active;
};

struct _entitasIndex {
	gint value;
};

struct _entitasLayer {
	gint value;
};

struct _entitasPosition {
	gdouble x;
	gdouble y;
};

struct _entitasScale {
	gdouble x;
	gdouble y;
};

struct _entitasSprite {
	SDL_Surface* surface;
};

struct _entitasText {
	gchar* text;
	SDL_Surface* surface;
};

struct _entitasTint {
	gint r;
	gint g;
	gint b;
	gint a;
};

struct _entitasTween {
	gdouble min;
	gdouble max;
	gdouble speed;
	gboolean repeat;
	gboolean active;
};

struct _entitasVelocity {
	gdouble x;
	gdouble y;
};

struct _entitasEntity {
	gint id;
	gchar* name;
	gint pool;
	guint64 mask;
	entitasBackground* background;
	entitasBounds* bounds;
	entitasBullet* bullet;
	entitasEnemy1* enemy1;
	entitasEnemy2* enemy2;
	entitasEnemy3* enemy3;
	entitasExpires* expires;
	entitasHealth* health;
	entitasHud* hud;
	entitasIndex* index;
	entitasLayer* layer;
	entitasPosition* position;
	entitasScale* scale;
	entitasSprite* sprite;
	entitasText* text;
	entitasTint* tint;
	entitasTween* tween;
	entitasVelocity* velocity;
};

struct _Game {
	gdouble mark1;
	gdouble mark2;
	gdouble delta;
	gdouble mouseX;
	gdouble mouseY;
	gboolean mouseDown;
	gboolean running;
	guint8 keys[256];
	SDL_Event evt;
	SDL_Surface* surface;
	entitasEntity* player;
	Factory* factory;
	GList* sprites;
};

typedef enum  {
	POOL_BACKGROUND,
	POOL_ENEMY1,
	POOL_ENEMY2,
	POOL_ENEMY3,
	POOL_PLAYER,
	POOL_BULLET,
	POOL_EXPLOSION,
	POOL_BANG,
	POOL_PARTICLE,
	POOL_HUD,
	POOL_Count
} Pool;

struct _Factory {
	entitasEntity pool[20];
	gint id;
	SDL_Surface** cache;
	gint cache_length1;
};



void game_free (Game* self);
GType entitas_entity_get_type (void) G_GNUC_CONST;
GType entitas_background_get_type (void) G_GNUC_CONST;
entitasBackground* entitas_background_dup (const entitasBackground* self);
void entitas_background_free (entitasBackground* self);
GType entitas_bounds_get_type (void) G_GNUC_CONST;
entitasBounds* entitas_bounds_dup (const entitasBounds* self);
void entitas_bounds_free (entitasBounds* self);
GType entitas_bullet_get_type (void) G_GNUC_CONST;
entitasBullet* entitas_bullet_dup (const entitasBullet* self);
void entitas_bullet_free (entitasBullet* self);
GType entitas_enemy1_get_type (void) G_GNUC_CONST;
entitasEnemy1* entitas_enemy1_dup (const entitasEnemy1* self);
void entitas_enemy1_free (entitasEnemy1* self);
GType entitas_enemy2_get_type (void) G_GNUC_CONST;
entitasEnemy2* entitas_enemy2_dup (const entitasEnemy2* self);
void entitas_enemy2_free (entitasEnemy2* self);
GType entitas_enemy3_get_type (void) G_GNUC_CONST;
entitasEnemy3* entitas_enemy3_dup (const entitasEnemy3* self);
void entitas_enemy3_free (entitasEnemy3* self);
GType entitas_expires_get_type (void) G_GNUC_CONST;
entitasExpires* entitas_expires_dup (const entitasExpires* self);
void entitas_expires_free (entitasExpires* self);
GType entitas_health_get_type (void) G_GNUC_CONST;
entitasHealth* entitas_health_dup (const entitasHealth* self);
void entitas_health_free (entitasHealth* self);
GType entitas_hud_get_type (void) G_GNUC_CONST;
entitasHud* entitas_hud_dup (const entitasHud* self);
void entitas_hud_free (entitasHud* self);
GType entitas_index_get_type (void) G_GNUC_CONST;
entitasIndex* entitas_index_dup (const entitasIndex* self);
void entitas_index_free (entitasIndex* self);
GType entitas_layer_get_type (void) G_GNUC_CONST;
entitasLayer* entitas_layer_dup (const entitasLayer* self);
void entitas_layer_free (entitasLayer* self);
GType entitas_position_get_type (void) G_GNUC_CONST;
entitasPosition* entitas_position_dup (const entitasPosition* self);
void entitas_position_free (entitasPosition* self);
GType entitas_scale_get_type (void) G_GNUC_CONST;
entitasScale* entitas_scale_dup (const entitasScale* self);
void entitas_scale_free (entitasScale* self);
GType entitas_sprite_get_type (void) G_GNUC_CONST;
entitasSprite* entitas_sprite_dup (const entitasSprite* self);
void entitas_sprite_free (entitasSprite* self);
GType entitas_text_get_type (void) G_GNUC_CONST;
entitasText* entitas_text_dup (const entitasText* self);
void entitas_text_free (entitasText* self);
void entitas_text_copy (const entitasText* self, entitasText* dest);
void entitas_text_destroy (entitasText* self);
GType entitas_tint_get_type (void) G_GNUC_CONST;
entitasTint* entitas_tint_dup (const entitasTint* self);
void entitas_tint_free (entitasTint* self);
GType entitas_tween_get_type (void) G_GNUC_CONST;
entitasTween* entitas_tween_dup (const entitasTween* self);
void entitas_tween_free (entitasTween* self);
GType entitas_velocity_get_type (void) G_GNUC_CONST;
entitasVelocity* entitas_velocity_dup (const entitasVelocity* self);
void entitas_velocity_free (entitasVelocity* self);
entitasEntity* entitas_entity_dup (const entitasEntity* self);
void entitas_entity_free (entitasEntity* self);
void entitas_entity_copy (const entitasEntity* self, entitasEntity* dest);
void entitas_entity_destroy (entitasEntity* self);
void factory_free (Factory* self);
static void game_instance_init (Game * self);
void game_initialize (Game* self);
Factory* factory_new (void);
entitasEntity* factory_createBackground (Factory* self, gint index, gint tile);
GType pool_get_type (void) G_GNUC_CONST;
entitasEntity* factory_createPlayer (Factory* self, gint index);
gboolean entitas_entity_isActive (entitasEntity *self);
gchar* entitas_entity_toString (entitasEntity *self);
void game_start (Game* self);
void game_processEvents (Game* self);
void game_update (Game* self);
Game* game_new (void);


void game_initialize (Game* self) {
	Factory* _tmp0_ = NULL;
	Factory* _tmp1_ = NULL;
	Factory* _tmp2_ = NULL;
	Factory* _tmp3_ = NULL;
	entitasEntity* _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = factory_new ();
	_factory_free0 (self->factory);
	self->factory = _tmp0_;
	_tmp1_ = self->factory;
	factory_createBackground (_tmp1_, (gint) POOL_BACKGROUND, 0);
	_tmp2_ = self->factory;
	factory_createBackground (_tmp2_, (gint) POOL_BACKGROUND, 1);
	_tmp3_ = self->factory;
	_tmp4_ = factory_createPlayer (_tmp3_, (gint) POOL_PLAYER);
	self->player = _tmp4_;
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp5_ = FALSE;
			_tmp5_ = TRUE;
			while (TRUE) {
				Factory* _tmp7_ = NULL;
				gint _tmp8_ = 0;
				gboolean _tmp9_ = FALSE;
				Factory* _tmp10_ = NULL;
				gint _tmp11_ = 0;
				gchar* _tmp12_ = NULL;
				gchar* _tmp13_ = NULL;
				if (!_tmp5_) {
					gint _tmp6_ = 0;
					_tmp6_ = i;
					i = _tmp6_ + 1;
				}
				_tmp5_ = FALSE;
				if (!(i <= 19)) {
					break;
				}
				_tmp7_ = self->factory;
				_tmp8_ = i;
				_tmp9_ = entitas_entity_isActive (&_tmp7_->pool[_tmp8_]);
				if (!_tmp9_) {
					continue;
				}
				_tmp10_ = self->factory;
				_tmp11_ = i;
				_tmp12_ = entitas_entity_toString (&_tmp10_->pool[_tmp11_]);
				_tmp13_ = _tmp12_;
				g_print ("%s\n", _tmp13_);
				_g_free0 (_tmp13_);
			}
		}
	}
}


void game_start (Game* self) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	self->running = TRUE;
	_tmp0_ = emscripten_get_now ();
	self->mark1 = _tmp0_ / 1000;
}


void game_processEvents (Game* self) {
	g_return_if_fail (self != NULL);
	while (TRUE) {
		SDL_Event _tmp0_ = {0};
		gint _tmp1_ = 0;
		SDL_Event _tmp2_ = {0};
		gint _tmp3_ = 0;
		_tmp1_ = SDL_PollEvent (&_tmp0_);
		self->evt = _tmp0_;
		if (!(_tmp1_ != 0)) {
			break;
		}
		_tmp2_ = self->evt;
		_tmp3_ = _tmp2_.type;
		switch (_tmp3_) {
			case SDL_QUIT:
			{
				{
					self->running = FALSE;
				}
				break;
			}
			case SDL_KEYDOWN:
			{
				{
					SDL_Event _tmp4_ = {0};
					SDL_KeyboardEvent _tmp5_ = {0};
					SDL_keysym _tmp6_ = {0};
					int _tmp7_ = 0;
					guint8 _tmp8_ = 0U;
					_tmp4_ = self->evt;
					_tmp5_ = _tmp4_.key;
					_tmp6_ = _tmp5_.keysym;
					_tmp7_ = _tmp6_.sym;
					self->keys[_tmp7_] = (guint8) 1;
					_tmp8_ = self->keys[_tmp7_];
				}
				break;
			}
			case SDL_KEYUP:
			{
				{
					SDL_Event _tmp9_ = {0};
					SDL_KeyboardEvent _tmp10_ = {0};
					SDL_keysym _tmp11_ = {0};
					int _tmp12_ = 0;
					guint8 _tmp13_ = 0U;
					_tmp9_ = self->evt;
					_tmp10_ = _tmp9_.key;
					_tmp11_ = _tmp10_.keysym;
					_tmp12_ = _tmp11_.sym;
					self->keys[_tmp12_] = (guint8) 0;
					_tmp13_ = self->keys[_tmp12_];
				}
				break;
			}
			case SDL_MOUSEMOTION:
			{
				{
					SDL_Event _tmp14_ = {0};
					SDL_MouseMotionEvent _tmp15_ = {0};
					guint16 _tmp16_ = 0U;
					SDL_Event _tmp17_ = {0};
					SDL_MouseMotionEvent _tmp18_ = {0};
					guint16 _tmp19_ = 0U;
					_tmp14_ = self->evt;
					_tmp15_ = _tmp14_.motion;
					_tmp16_ = _tmp15_.x;
					self->mouseX = (gdouble) _tmp16_;
					_tmp17_ = self->evt;
					_tmp18_ = _tmp17_.motion;
					_tmp19_ = _tmp18_.y;
					self->mouseY = (gdouble) _tmp19_;
				}
				break;
			}
			case SDL_MOUSEBUTTONDOWN:
			{
				{
					self->mouseDown = TRUE;
				}
				break;
			}
			case SDL_MOUSEBUTTONUP:
			{
				{
					self->mouseDown = FALSE;
				}
				break;
			}
			default:
			break;
		}
	}
}


void game_update (Game* self) {
	gdouble _tmp0_ = 0.0;
	gdouble _tmp1_ = 0.0;
	gdouble _tmp2_ = 0.0;
	gdouble _tmp3_ = 0.0;
	entitasEntity* _tmp4_ = NULL;
	entitasBounds* _tmp5_ = NULL;
	gdouble _tmp6_ = 0.0;
	entitasEntity* _tmp7_ = NULL;
	entitasBounds* _tmp8_ = NULL;
	gint _tmp9_ = 0;
	entitasEntity* _tmp10_ = NULL;
	entitasBounds* _tmp11_ = NULL;
	gdouble _tmp12_ = 0.0;
	entitasEntity* _tmp13_ = NULL;
	entitasBounds* _tmp14_ = NULL;
	gint _tmp15_ = 0;
	SDL_Surface* _tmp16_ = NULL;
	SDL_Surface* _tmp17_ = NULL;
	SDL_PixelFormat* _tmp18_ = NULL;
	guint32 _tmp19_ = 0U;
	SDL_Surface* _tmp52_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = emscripten_get_now ();
	self->mark2 = _tmp0_ / 1000;
	_tmp1_ = self->mark2;
	_tmp2_ = self->mark1;
	self->delta = _tmp1_ - _tmp2_;
	_tmp3_ = self->mark2;
	self->mark1 = _tmp3_;
	game_processEvents (self);
	_tmp4_ = self->player;
	_tmp5_ = (*_tmp4_).bounds;
	_tmp6_ = self->mouseX;
	_tmp7_ = self->player;
	_tmp8_ = (*_tmp7_).bounds;
	_tmp9_ = (*_tmp8_).w;
	(*_tmp5_).x = (gint) (_tmp6_ - (_tmp9_ / 2));
	_tmp10_ = self->player;
	_tmp11_ = (*_tmp10_).bounds;
	_tmp12_ = self->mouseY;
	_tmp13_ = self->player;
	_tmp14_ = (*_tmp13_).bounds;
	_tmp15_ = (*_tmp14_).h;
	(*_tmp11_).y = (gint) (_tmp12_ - (_tmp15_ / 2));
	_tmp16_ = self->surface;
	_tmp17_ = self->surface;
	_tmp18_ = _tmp17_->format;
	_tmp19_ = SDL_MapRGB (_tmp18_, (guchar) 255, (guchar) 0, (guchar) 0);
	SDL_FillRect (_tmp16_, NULL, _tmp19_);
	{
		gint i = 0;
		i = 0;
		{
			gboolean _tmp20_ = FALSE;
			_tmp20_ = TRUE;
			while (TRUE) {
				Factory* _tmp22_ = NULL;
				gint _tmp23_ = 0;
				gboolean _tmp24_ = FALSE;
				Factory* _tmp25_ = NULL;
				gint _tmp26_ = 0;
				entitasEntity _tmp27_ = {0};
				entitasSprite* _tmp28_ = NULL;
				SDL_Surface* _tmp29_ = NULL;
				SDL_Surface* _tmp30_ = NULL;
				Factory* _tmp31_ = NULL;
				gint _tmp32_ = 0;
				entitasEntity _tmp33_ = {0};
				entitasBounds* _tmp34_ = NULL;
				gint _tmp35_ = 0;
				Factory* _tmp36_ = NULL;
				gint _tmp37_ = 0;
				entitasEntity _tmp38_ = {0};
				entitasBounds* _tmp39_ = NULL;
				gint _tmp40_ = 0;
				Factory* _tmp41_ = NULL;
				gint _tmp42_ = 0;
				entitasEntity _tmp43_ = {0};
				entitasBounds* _tmp44_ = NULL;
				gint _tmp45_ = 0;
				Factory* _tmp46_ = NULL;
				gint _tmp47_ = 0;
				entitasEntity _tmp48_ = {0};
				entitasBounds* _tmp49_ = NULL;
				gint _tmp50_ = 0;
				SDL_Rect _tmp51_ = {0};
				if (!_tmp20_) {
					gint _tmp21_ = 0;
					_tmp21_ = i;
					i = _tmp21_ + 1;
				}
				_tmp20_ = FALSE;
				if (!(i <= 19)) {
					break;
				}
				_tmp22_ = self->factory;
				_tmp23_ = i;
				_tmp24_ = entitas_entity_isActive (&_tmp22_->pool[_tmp23_]);
				if (!_tmp24_) {
					continue;
				}
				_tmp25_ = self->factory;
				_tmp26_ = i;
				_tmp27_ = _tmp25_->pool[_tmp26_];
				_tmp28_ = _tmp27_.sprite;
				_tmp29_ = (*_tmp28_).surface;
				_tmp30_ = self->surface;
				_tmp31_ = self->factory;
				_tmp32_ = i;
				_tmp33_ = _tmp31_->pool[_tmp32_];
				_tmp34_ = _tmp33_.bounds;
				_tmp35_ = (*_tmp34_).x;
				_tmp36_ = self->factory;
				_tmp37_ = i;
				_tmp38_ = _tmp36_->pool[_tmp37_];
				_tmp39_ = _tmp38_.bounds;
				_tmp40_ = (*_tmp39_).y;
				_tmp41_ = self->factory;
				_tmp42_ = i;
				_tmp43_ = _tmp41_->pool[_tmp42_];
				_tmp44_ = _tmp43_.bounds;
				_tmp45_ = (*_tmp44_).w;
				_tmp46_ = self->factory;
				_tmp47_ = i;
				_tmp48_ = _tmp46_->pool[_tmp47_];
				_tmp49_ = _tmp48_.bounds;
				_tmp50_ = (*_tmp49_).h;
				_tmp51_.x = (gint16) _tmp35_;
				_tmp51_.y = (gint16) _tmp40_;
				_tmp51_.w = (guint16) ((gint16) _tmp45_);
				_tmp51_.h = (guint16) ((gint16) _tmp50_);
				SDL_UpperBlit (_tmp29_, NULL, _tmp30_, &_tmp51_);
			}
		}
	}
	_tmp52_ = self->surface;
	SDL_Flip (_tmp52_);
}


Game* game_new (void) {
	Game* self;
	self = g_slice_new0 (Game);
	game_instance_init (self);
	return self;
}


static void game_instance_init (Game * self) {
	self->sprites = NULL;
}


void game_free (Game* self) {
	_factory_free0 (self->factory);
	_g_list_free0 (self->sprites);
	g_slice_free (Game, self);
}



