/* hashmap.c generated by valac 0.34.7, the Vala compiler
 * generated from hashmap.gs, do not modify */


#include <glib.h>
#include <glib-object.h>

typedef struct _HashMap HashMap;
#define _g_list_free0(var) ((var == NULL) ? NULL : (var = (g_list_free (var), NULL)))

struct _HashMap {
	GList* keys;
	GList* data;
};



void hash_map_free (HashMap* self);
static void hash_map_instance_init (HashMap * self);
gboolean hash_map_hasKey (HashMap* self, gconstpointer key);
void hash_map_add (HashMap* self, gconstpointer key, gconstpointer value);
HashMap* hash_map_new (void);


gboolean hash_map_hasKey (HashMap* self, gconstpointer key) {
	gboolean result = FALSE;
	GList* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->keys;
	{
		GList* k_collection = NULL;
		GList* k_it = NULL;
		k_collection = _tmp0_;
		for (k_it = k_collection; k_it != NULL; k_it = k_it->next) {
			gpointer k = NULL;
			k = k_it->data;
			{
				gconstpointer _tmp1_ = NULL;
				gconstpointer _tmp2_ = NULL;
				_tmp1_ = k;
				_tmp2_ = key;
				if (_tmp1_ == _tmp2_) {
					result = TRUE;
					return result;
				}
			}
		}
	}
	result = FALSE;
	return result;
}


void hash_map_add (HashMap* self, gconstpointer key, gconstpointer value) {
	GList* _tmp0_ = NULL;
	gconstpointer _tmp3_ = NULL;
	gconstpointer _tmp4_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = self->keys;
	{
		GList* k_collection = NULL;
		GList* k_it = NULL;
		k_collection = _tmp0_;
		for (k_it = k_collection; k_it != NULL; k_it = k_it->next) {
			gpointer k = NULL;
			k = k_it->data;
			{
				gconstpointer _tmp1_ = NULL;
				gconstpointer _tmp2_ = NULL;
				_tmp1_ = k;
				_tmp2_ = key;
				if (_tmp1_ == _tmp2_) {
					return;
				}
			}
		}
	}
	_tmp3_ = key;
	self->keys = g_list_append (self->keys, _tmp3_);
	_tmp4_ = value;
	self->data = g_list_append (self->data, _tmp4_);
}


HashMap* hash_map_new (void) {
	HashMap* self;
	self = g_slice_new0 (HashMap);
	hash_map_instance_init (self);
	return self;
}


static void hash_map_instance_init (HashMap * self) {
	self->keys = NULL;
	self->data = NULL;
}


void hash_map_free (HashMap* self) {
	_g_list_free0 (self->keys);
	_g_list_free0 (self->data);
	g_slice_free (HashMap, self);
}



