/* hello_world.c generated by valac 0.34.7, the Vala compiler
 * generated from hello_world.gs, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <SDL.h>
#include <stdlib.h>
#include <string.h>
#include <emscripten.h>



extern SDL_Surface* surface;
SDL_Surface* surface = NULL;

void _vala_main (gchar** args, int args_length1);
void main_loop (void* game);
static void _main_loop_em_arg_callback_func (void* ctx);


static void _main_loop_em_arg_callback_func (void* ctx) {
	main_loop (ctx);
}


void _vala_main (gchar** args, int args_length1) {
	gint x = 0;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	SDL_Surface* _tmp3_ = NULL;
	SDL_Surface* _tmp4_ = NULL;
	x = 42;
	_tmp0_ = x;
	g_print ("Hello World %d\n", _tmp0_);
	_tmp1_ = SDL_Init ((guint32) SDL_INIT_VIDEO);
	if (_tmp1_ < 0) {
		const gchar* _tmp2_ = NULL;
		_tmp2_ = SDL_GetError ();
		g_print ("Unable to init SDL %s\n", _tmp2_);
		return;
	}
	_tmp3_ = SDL_SetVideoMode (800, 300, 32, (guint32) (SDL_HWSURFACE | SDL_DOUBLEBUF));
	surface = _tmp3_;
	_tmp4_ = surface;
	if (_tmp4_ == NULL) {
		const gchar* _tmp5_ = NULL;
		_tmp5_ = SDL_GetError ();
		g_print ("Unable to set video %s\n", _tmp5_);
		return;
	}
	SDL_WM_SetCaption ("Hello", "");
	emscripten_set_main_loop_arg (_main_loop_em_arg_callback_func, NULL, 0, 1);
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	_vala_main (argv, argc);
	return 0;
}


void main_loop (void* game) {
	SDL_Event event = {0};
	while (TRUE) {
		SDL_Event _tmp0_ = {0};
		gint _tmp1_ = 0;
		SDL_Event _tmp2_ = {0};
		guchar _tmp3_ = '\0';
		SDL_Surface* _tmp4_ = NULL;
		SDL_Surface* _tmp5_ = NULL;
		SDL_PixelFormat* _tmp6_ = NULL;
		guint32 _tmp7_ = 0U;
		_tmp1_ = SDL_PollEvent (&_tmp0_);
		event = _tmp0_;
		if (!(_tmp1_ > 0)) {
			break;
		}
		_tmp2_ = event;
		_tmp3_ = _tmp2_.type;
		switch (_tmp3_) {
			case SDL_QUIT:
			{
				{
				}
				break;
			}
			default:
			break;
		}
		_tmp4_ = surface;
		_tmp5_ = surface;
		_tmp6_ = _tmp5_->format;
		_tmp7_ = SDL_MapRGB (_tmp6_, (guchar) 255, (guchar) 0, (guchar) 0);
		SDL_FillRect (_tmp4_, NULL, _tmp7_);
	}
}



