/* components.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from components.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <string.h>
#include <stdlib.h>
#include <SDL2/SDL_mixer.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_render.h>
#include <SDL2/SDL_rect.h>


#define TYPE_ACTOR (actor_get_type ())

#define TYPE_CATEGORY (category_get_type ())

#define TYPE_EFFECT (effect_get_type ())

#define TYPE_ID (id_get_type ())
typedef struct _Id Id;

#define TYPE_NAME (name_get_type ())
typedef struct _Name Name;
#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_ACTIVE (active_get_type ())
typedef struct _Active Active;

#define TYPE_ACTOR_TYPE (actor_type_get_type ())
typedef struct _ActorType ActorType;

#define TYPE_ACTOR_STYLE (actor_style_get_type ())
typedef struct _ActorStyle ActorStyle;

#define TYPE_SOUND (sound_get_type ())
typedef struct _Sound Sound;

#define TYPE_POINT2D (point2d_get_type ())
typedef struct _Point2d Point2d;

#define TYPE_VECTOR2D (vector2d_get_type ())
typedef struct _Vector2d Vector2d;

#define TYPE_SCALE (scale_get_type ())
typedef struct _Scale Scale;

#define TYPE_COLOR (color_get_type ())
typedef struct _Color Color;

#define TYPE_HEALTH (health_get_type ())
typedef struct _Health Health;

#define TYPE_DURATION (duration_get_type ())
typedef struct _Duration Duration;

#define TYPE_TWEEN (tween_get_type ())
typedef struct _Tween Tween;

#define TYPE_SPRITE (sprite_get_type ())
typedef struct _Sprite Sprite;

#define TYPE_ENTITY (entity_get_type ())
typedef struct _Entity Entity;
#define _sound_free0(var) ((var == NULL) ? NULL : (var = (sound_free (var), NULL)))
#define _color_free0(var) ((var == NULL) ? NULL : (var = (color_free (var), NULL)))
#define _duration_free0(var) ((var == NULL) ? NULL : (var = (duration_free (var), NULL)))
#define _health_free0(var) ((var == NULL) ? NULL : (var = (health_free (var), NULL)))
#define _tween_free0(var) ((var == NULL) ? NULL : (var = (tween_free (var), NULL)))
#define _vector2d_free0(var) ((var == NULL) ? NULL : (var = (vector2d_free (var), NULL)))

#define TYPE_METRICS (metrics_get_type ())
typedef struct _Metrics Metrics;

typedef enum  {
	ACTOR_BACKGROUND,
	ACTOR_ENEMY1,
	ACTOR_ENEMY2,
	ACTOR_ENEMY3,
	ACTOR_PLAYER,
	ACTOR_BULLET,
	ACTOR_EXPLOSION,
	ACTOR_BANG,
	ACTOR_PARTICLE
} Actor;

typedef enum  {
	CATEGORY_BACKGROUND,
	CATEGORY_BULLET,
	CATEGORY_ENEMY,
	CATEGORY_EXPLOSION,
	CATEGORY_PARTICLE,
	CATEGORY_PLAYER
} Category;

typedef enum  {
	EFFECT_PEW,
	EFFECT_SMALLASPLODE,
	EFFECT_ASPLODE
} Effect;

struct _Id {
	gint id;
};

struct _Name {
	gchar* name;
};

struct _Active {
	gboolean active;
};

struct _ActorType {
	Actor isA;
};

struct _ActorStyle {
	Category isA;
};

struct _Sound {
	Mix_Chunk* effect;
};

struct _Point2d {
	gdouble x;
	gdouble y;
};

struct _Vector2d {
	gdouble x;
	gdouble y;
};

struct _Scale {
	gdouble x;
	gdouble y;
};

struct _Color {
	gint r;
	gint g;
	gint b;
	gint a;
};

struct _Health {
	gint current;
	gint maximum;
};

struct _Duration {
	gdouble timer;
};

struct _Tween {
	gdouble min;
	gdouble max;
	gdouble speed;
	gboolean repeat;
	gboolean active;
};

struct _Sprite {
	SDL_Texture* texture;
	gint width;
	gint height;
};

struct _Entity {
	Id id;
	Name name;
	Active active;
	ActorType actor;
	ActorStyle style;
	Point2d position;
	SDL_Rect bounds;
	Vector2d scale;
	Sprite sprite;
	Sound* sound;
	Color* tint;
	Duration* expires;
	Health* health;
	Tween* tween;
	Vector2d* velocity;
};

struct _Metrics {
	gint bullet;
	gint enemy1;
	gint enemy2;
	gint enemy3;
	gint explosion;
	gint bang;
	gint particle;
	gint count;
};



GType actor_get_type (void) G_GNUC_CONST;
GType category_get_type (void) G_GNUC_CONST;
GType effect_get_type (void) G_GNUC_CONST;
GType id_get_type (void) G_GNUC_CONST;
Id* id_dup (const Id* self);
void id_free (Id* self);
GType name_get_type (void) G_GNUC_CONST;
Name* name_dup (const Name* self);
void name_free (Name* self);
void name_copy (const Name* self, Name* dest);
void name_destroy (Name* self);
GType active_get_type (void) G_GNUC_CONST;
Active* active_dup (const Active* self);
void active_free (Active* self);
GType actor_type_get_type (void) G_GNUC_CONST;
ActorType* actor_type_dup (const ActorType* self);
void actor_type_free (ActorType* self);
GType actor_style_get_type (void) G_GNUC_CONST;
ActorStyle* actor_style_dup (const ActorStyle* self);
void actor_style_free (ActorStyle* self);
GType sound_get_type (void) G_GNUC_CONST;
Sound* sound_dup (const Sound* self);
void sound_free (Sound* self);
GType point2d_get_type (void) G_GNUC_CONST;
Point2d* point2d_dup (const Point2d* self);
void point2d_free (Point2d* self);
GType vector2d_get_type (void) G_GNUC_CONST;
Vector2d* vector2d_dup (const Vector2d* self);
void vector2d_free (Vector2d* self);
GType scale_get_type (void) G_GNUC_CONST;
Scale* scale_dup (const Scale* self);
void scale_free (Scale* self);
GType color_get_type (void) G_GNUC_CONST;
Color* color_dup (const Color* self);
void color_free (Color* self);
GType health_get_type (void) G_GNUC_CONST;
Health* health_dup (const Health* self);
void health_free (Health* self);
GType duration_get_type (void) G_GNUC_CONST;
Duration* duration_dup (const Duration* self);
void duration_free (Duration* self);
GType tween_get_type (void) G_GNUC_CONST;
Tween* tween_dup (const Tween* self);
void tween_free (Tween* self);
GType sprite_get_type (void) G_GNUC_CONST;
Sprite* sprite_dup (const Sprite* self);
void sprite_free (Sprite* self);
GType entity_get_type (void) G_GNUC_CONST;
Entity* entity_dup (const Entity* self);
void entity_free (Entity* self);
void entity_copy (const Entity* self, Entity* dest);
void entity_destroy (Entity* self);
GType metrics_get_type (void) G_GNUC_CONST;
Metrics* metrics_dup (const Metrics* self);
void metrics_free (Metrics* self);
void metrics_init (Metrics *self, gint bullet, gint enemy1, gint enemy2, gint enemy3, gint explosion, gint bang, gint particle, gint count);


GType actor_get_type (void) {
	static volatile gsize actor_type_id__volatile = 0;
	if (g_once_init_enter (&actor_type_id__volatile)) {
		static const GEnumValue values[] = {{ACTOR_BACKGROUND, "ACTOR_BACKGROUND", "background"}, {ACTOR_ENEMY1, "ACTOR_ENEMY1", "enemy1"}, {ACTOR_ENEMY2, "ACTOR_ENEMY2", "enemy2"}, {ACTOR_ENEMY3, "ACTOR_ENEMY3", "enemy3"}, {ACTOR_PLAYER, "ACTOR_PLAYER", "player"}, {ACTOR_BULLET, "ACTOR_BULLET", "bullet"}, {ACTOR_EXPLOSION, "ACTOR_EXPLOSION", "explosion"}, {ACTOR_BANG, "ACTOR_BANG", "bang"}, {ACTOR_PARTICLE, "ACTOR_PARTICLE", "particle"}, {0, NULL, NULL}};
		GType actor_type_id;
		actor_type_id = g_enum_register_static ("Actor", values);
		g_once_init_leave (&actor_type_id__volatile, actor_type_id);
	}
	return actor_type_id__volatile;
}


GType category_get_type (void) {
	static volatile gsize category_type_id__volatile = 0;
	if (g_once_init_enter (&category_type_id__volatile)) {
		static const GEnumValue values[] = {{CATEGORY_BACKGROUND, "CATEGORY_BACKGROUND", "background"}, {CATEGORY_BULLET, "CATEGORY_BULLET", "bullet"}, {CATEGORY_ENEMY, "CATEGORY_ENEMY", "enemy"}, {CATEGORY_EXPLOSION, "CATEGORY_EXPLOSION", "explosion"}, {CATEGORY_PARTICLE, "CATEGORY_PARTICLE", "particle"}, {CATEGORY_PLAYER, "CATEGORY_PLAYER", "player"}, {0, NULL, NULL}};
		GType category_type_id;
		category_type_id = g_enum_register_static ("Category", values);
		g_once_init_leave (&category_type_id__volatile, category_type_id);
	}
	return category_type_id__volatile;
}


GType effect_get_type (void) {
	static volatile gsize effect_type_id__volatile = 0;
	if (g_once_init_enter (&effect_type_id__volatile)) {
		static const GEnumValue values[] = {{EFFECT_PEW, "EFFECT_PEW", "pew"}, {EFFECT_SMALLASPLODE, "EFFECT_SMALLASPLODE", "smallasplode"}, {EFFECT_ASPLODE, "EFFECT_ASPLODE", "asplode"}, {0, NULL, NULL}};
		GType effect_type_id;
		effect_type_id = g_enum_register_static ("Effect", values);
		g_once_init_leave (&effect_type_id__volatile, effect_type_id);
	}
	return effect_type_id__volatile;
}


Id* id_dup (const Id* self) {
	Id* dup;
	dup = g_new0 (Id, 1);
	memcpy (dup, self, sizeof (Id));
	return dup;
}


void id_free (Id* self) {
	g_free (self);
}


GType id_get_type (void) {
	static volatile gsize id_type_id__volatile = 0;
	if (g_once_init_enter (&id_type_id__volatile)) {
		GType id_type_id;
		id_type_id = g_boxed_type_register_static ("Id", (GBoxedCopyFunc) id_dup, (GBoxedFreeFunc) id_free);
		g_once_init_leave (&id_type_id__volatile, id_type_id);
	}
	return id_type_id__volatile;
}


void name_copy (const Name* self, Name* dest) {
	const gchar* _tmp0_;
	gchar* _tmp1_;
	_tmp0_ = (*self).name;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 ((*dest).name);
	(*dest).name = _tmp1_;
}


void name_destroy (Name* self) {
	_g_free0 ((*self).name);
}


Name* name_dup (const Name* self) {
	Name* dup;
	dup = g_new0 (Name, 1);
	name_copy (self, dup);
	return dup;
}


void name_free (Name* self) {
	name_destroy (self);
	g_free (self);
}


GType name_get_type (void) {
	static volatile gsize name_type_id__volatile = 0;
	if (g_once_init_enter (&name_type_id__volatile)) {
		GType name_type_id;
		name_type_id = g_boxed_type_register_static ("Name", (GBoxedCopyFunc) name_dup, (GBoxedFreeFunc) name_free);
		g_once_init_leave (&name_type_id__volatile, name_type_id);
	}
	return name_type_id__volatile;
}


Active* active_dup (const Active* self) {
	Active* dup;
	dup = g_new0 (Active, 1);
	memcpy (dup, self, sizeof (Active));
	return dup;
}


void active_free (Active* self) {
	g_free (self);
}


GType active_get_type (void) {
	static volatile gsize active_type_id__volatile = 0;
	if (g_once_init_enter (&active_type_id__volatile)) {
		GType active_type_id;
		active_type_id = g_boxed_type_register_static ("Active", (GBoxedCopyFunc) active_dup, (GBoxedFreeFunc) active_free);
		g_once_init_leave (&active_type_id__volatile, active_type_id);
	}
	return active_type_id__volatile;
}


ActorType* actor_type_dup (const ActorType* self) {
	ActorType* dup;
	dup = g_new0 (ActorType, 1);
	memcpy (dup, self, sizeof (ActorType));
	return dup;
}


void actor_type_free (ActorType* self) {
	g_free (self);
}


GType actor_type_get_type (void) {
	static volatile gsize actor_type_type_id__volatile = 0;
	if (g_once_init_enter (&actor_type_type_id__volatile)) {
		GType actor_type_type_id;
		actor_type_type_id = g_boxed_type_register_static ("ActorType", (GBoxedCopyFunc) actor_type_dup, (GBoxedFreeFunc) actor_type_free);
		g_once_init_leave (&actor_type_type_id__volatile, actor_type_type_id);
	}
	return actor_type_type_id__volatile;
}


ActorStyle* actor_style_dup (const ActorStyle* self) {
	ActorStyle* dup;
	dup = g_new0 (ActorStyle, 1);
	memcpy (dup, self, sizeof (ActorStyle));
	return dup;
}


void actor_style_free (ActorStyle* self) {
	g_free (self);
}


GType actor_style_get_type (void) {
	static volatile gsize actor_style_type_id__volatile = 0;
	if (g_once_init_enter (&actor_style_type_id__volatile)) {
		GType actor_style_type_id;
		actor_style_type_id = g_boxed_type_register_static ("ActorStyle", (GBoxedCopyFunc) actor_style_dup, (GBoxedFreeFunc) actor_style_free);
		g_once_init_leave (&actor_style_type_id__volatile, actor_style_type_id);
	}
	return actor_style_type_id__volatile;
}


Sound* sound_dup (const Sound* self) {
	Sound* dup;
	dup = g_new0 (Sound, 1);
	memcpy (dup, self, sizeof (Sound));
	return dup;
}


void sound_free (Sound* self) {
	g_free (self);
}


GType sound_get_type (void) {
	static volatile gsize sound_type_id__volatile = 0;
	if (g_once_init_enter (&sound_type_id__volatile)) {
		GType sound_type_id;
		sound_type_id = g_boxed_type_register_static ("Sound", (GBoxedCopyFunc) sound_dup, (GBoxedFreeFunc) sound_free);
		g_once_init_leave (&sound_type_id__volatile, sound_type_id);
	}
	return sound_type_id__volatile;
}


Point2d* point2d_dup (const Point2d* self) {
	Point2d* dup;
	dup = g_new0 (Point2d, 1);
	memcpy (dup, self, sizeof (Point2d));
	return dup;
}


void point2d_free (Point2d* self) {
	g_free (self);
}


GType point2d_get_type (void) {
	static volatile gsize point2d_type_id__volatile = 0;
	if (g_once_init_enter (&point2d_type_id__volatile)) {
		GType point2d_type_id;
		point2d_type_id = g_boxed_type_register_static ("Point2d", (GBoxedCopyFunc) point2d_dup, (GBoxedFreeFunc) point2d_free);
		g_once_init_leave (&point2d_type_id__volatile, point2d_type_id);
	}
	return point2d_type_id__volatile;
}


Vector2d* vector2d_dup (const Vector2d* self) {
	Vector2d* dup;
	dup = g_new0 (Vector2d, 1);
	memcpy (dup, self, sizeof (Vector2d));
	return dup;
}


void vector2d_free (Vector2d* self) {
	g_free (self);
}


GType vector2d_get_type (void) {
	static volatile gsize vector2d_type_id__volatile = 0;
	if (g_once_init_enter (&vector2d_type_id__volatile)) {
		GType vector2d_type_id;
		vector2d_type_id = g_boxed_type_register_static ("Vector2d", (GBoxedCopyFunc) vector2d_dup, (GBoxedFreeFunc) vector2d_free);
		g_once_init_leave (&vector2d_type_id__volatile, vector2d_type_id);
	}
	return vector2d_type_id__volatile;
}


Scale* scale_dup (const Scale* self) {
	Scale* dup;
	dup = g_new0 (Scale, 1);
	memcpy (dup, self, sizeof (Scale));
	return dup;
}


void scale_free (Scale* self) {
	g_free (self);
}


GType scale_get_type (void) {
	static volatile gsize scale_type_id__volatile = 0;
	if (g_once_init_enter (&scale_type_id__volatile)) {
		GType scale_type_id;
		scale_type_id = g_boxed_type_register_static ("Scale", (GBoxedCopyFunc) scale_dup, (GBoxedFreeFunc) scale_free);
		g_once_init_leave (&scale_type_id__volatile, scale_type_id);
	}
	return scale_type_id__volatile;
}


Color* color_dup (const Color* self) {
	Color* dup;
	dup = g_new0 (Color, 1);
	memcpy (dup, self, sizeof (Color));
	return dup;
}


void color_free (Color* self) {
	g_free (self);
}


GType color_get_type (void) {
	static volatile gsize color_type_id__volatile = 0;
	if (g_once_init_enter (&color_type_id__volatile)) {
		GType color_type_id;
		color_type_id = g_boxed_type_register_static ("Color", (GBoxedCopyFunc) color_dup, (GBoxedFreeFunc) color_free);
		g_once_init_leave (&color_type_id__volatile, color_type_id);
	}
	return color_type_id__volatile;
}


Health* health_dup (const Health* self) {
	Health* dup;
	dup = g_new0 (Health, 1);
	memcpy (dup, self, sizeof (Health));
	return dup;
}


void health_free (Health* self) {
	g_free (self);
}


GType health_get_type (void) {
	static volatile gsize health_type_id__volatile = 0;
	if (g_once_init_enter (&health_type_id__volatile)) {
		GType health_type_id;
		health_type_id = g_boxed_type_register_static ("Health", (GBoxedCopyFunc) health_dup, (GBoxedFreeFunc) health_free);
		g_once_init_leave (&health_type_id__volatile, health_type_id);
	}
	return health_type_id__volatile;
}


Duration* duration_dup (const Duration* self) {
	Duration* dup;
	dup = g_new0 (Duration, 1);
	memcpy (dup, self, sizeof (Duration));
	return dup;
}


void duration_free (Duration* self) {
	g_free (self);
}


GType duration_get_type (void) {
	static volatile gsize duration_type_id__volatile = 0;
	if (g_once_init_enter (&duration_type_id__volatile)) {
		GType duration_type_id;
		duration_type_id = g_boxed_type_register_static ("Duration", (GBoxedCopyFunc) duration_dup, (GBoxedFreeFunc) duration_free);
		g_once_init_leave (&duration_type_id__volatile, duration_type_id);
	}
	return duration_type_id__volatile;
}


Tween* tween_dup (const Tween* self) {
	Tween* dup;
	dup = g_new0 (Tween, 1);
	memcpy (dup, self, sizeof (Tween));
	return dup;
}


void tween_free (Tween* self) {
	g_free (self);
}


GType tween_get_type (void) {
	static volatile gsize tween_type_id__volatile = 0;
	if (g_once_init_enter (&tween_type_id__volatile)) {
		GType tween_type_id;
		tween_type_id = g_boxed_type_register_static ("Tween", (GBoxedCopyFunc) tween_dup, (GBoxedFreeFunc) tween_free);
		g_once_init_leave (&tween_type_id__volatile, tween_type_id);
	}
	return tween_type_id__volatile;
}


Sprite* sprite_dup (const Sprite* self) {
	Sprite* dup;
	dup = g_new0 (Sprite, 1);
	memcpy (dup, self, sizeof (Sprite));
	return dup;
}


void sprite_free (Sprite* self) {
	g_free (self);
}


GType sprite_get_type (void) {
	static volatile gsize sprite_type_id__volatile = 0;
	if (g_once_init_enter (&sprite_type_id__volatile)) {
		GType sprite_type_id;
		sprite_type_id = g_boxed_type_register_static ("Sprite", (GBoxedCopyFunc) sprite_dup, (GBoxedFreeFunc) sprite_free);
		g_once_init_leave (&sprite_type_id__volatile, sprite_type_id);
	}
	return sprite_type_id__volatile;
}


static gpointer _sound_dup0 (gpointer self) {
	return self ? sound_dup (self) : NULL;
}


static gpointer _color_dup0 (gpointer self) {
	return self ? color_dup (self) : NULL;
}


static gpointer _duration_dup0 (gpointer self) {
	return self ? duration_dup (self) : NULL;
}


static gpointer _health_dup0 (gpointer self) {
	return self ? health_dup (self) : NULL;
}


static gpointer _tween_dup0 (gpointer self) {
	return self ? tween_dup (self) : NULL;
}


static gpointer _vector2d_dup0 (gpointer self) {
	return self ? vector2d_dup (self) : NULL;
}


void entity_copy (const Entity* self, Entity* dest) {
	Id _tmp0_;
	Name _tmp1_;
	Name _tmp2_ = {0};
	Active _tmp3_;
	ActorType _tmp4_;
	ActorStyle _tmp5_;
	Point2d _tmp6_;
	SDL_Rect _tmp7_;
	Vector2d _tmp8_;
	Sprite _tmp9_;
	Sound* _tmp10_;
	Sound* _tmp11_;
	Color* _tmp12_;
	Color* _tmp13_;
	Duration* _tmp14_;
	Duration* _tmp15_;
	Health* _tmp16_;
	Health* _tmp17_;
	Tween* _tmp18_;
	Tween* _tmp19_;
	Vector2d* _tmp20_;
	Vector2d* _tmp21_;
	_tmp0_ = (*self).id;
	(*dest).id = _tmp0_;
	_tmp1_ = (*self).name;
	name_copy (&_tmp1_, &_tmp2_);
	name_destroy (&(*dest).name);
	(*dest).name = _tmp2_;
	_tmp3_ = (*self).active;
	(*dest).active = _tmp3_;
	_tmp4_ = (*self).actor;
	(*dest).actor = _tmp4_;
	_tmp5_ = (*self).style;
	(*dest).style = _tmp5_;
	_tmp6_ = (*self).position;
	(*dest).position = _tmp6_;
	_tmp7_ = (*self).bounds;
	(*dest).bounds = _tmp7_;
	_tmp8_ = (*self).scale;
	(*dest).scale = _tmp8_;
	_tmp9_ = (*self).sprite;
	(*dest).sprite = _tmp9_;
	_tmp10_ = (*self).sound;
	_tmp11_ = _sound_dup0 (_tmp10_);
	_sound_free0 ((*dest).sound);
	(*dest).sound = _tmp11_;
	_tmp12_ = (*self).tint;
	_tmp13_ = _color_dup0 (_tmp12_);
	_color_free0 ((*dest).tint);
	(*dest).tint = _tmp13_;
	_tmp14_ = (*self).expires;
	_tmp15_ = _duration_dup0 (_tmp14_);
	_duration_free0 ((*dest).expires);
	(*dest).expires = _tmp15_;
	_tmp16_ = (*self).health;
	_tmp17_ = _health_dup0 (_tmp16_);
	_health_free0 ((*dest).health);
	(*dest).health = _tmp17_;
	_tmp18_ = (*self).tween;
	_tmp19_ = _tween_dup0 (_tmp18_);
	_tween_free0 ((*dest).tween);
	(*dest).tween = _tmp19_;
	_tmp20_ = (*self).velocity;
	_tmp21_ = _vector2d_dup0 (_tmp20_);
	_vector2d_free0 ((*dest).velocity);
	(*dest).velocity = _tmp21_;
}


void entity_destroy (Entity* self) {
	name_destroy (&(*self).name);
	_sound_free0 ((*self).sound);
	_color_free0 ((*self).tint);
	_duration_free0 ((*self).expires);
	_health_free0 ((*self).health);
	_tween_free0 ((*self).tween);
	_vector2d_free0 ((*self).velocity);
}


Entity* entity_dup (const Entity* self) {
	Entity* dup;
	dup = g_new0 (Entity, 1);
	entity_copy (self, dup);
	return dup;
}


void entity_free (Entity* self) {
	entity_destroy (self);
	g_free (self);
}


GType entity_get_type (void) {
	static volatile gsize entity_type_id__volatile = 0;
	if (g_once_init_enter (&entity_type_id__volatile)) {
		GType entity_type_id;
		entity_type_id = g_boxed_type_register_static ("Entity", (GBoxedCopyFunc) entity_dup, (GBoxedFreeFunc) entity_free);
		g_once_init_leave (&entity_type_id__volatile, entity_type_id);
	}
	return entity_type_id__volatile;
}


void metrics_init (Metrics *self, gint bullet, gint enemy1, gint enemy2, gint enemy3, gint explosion, gint bang, gint particle, gint count) {
	gint _tmp0_;
	gint _tmp1_;
	gint _tmp2_;
	gint _tmp3_;
	gint _tmp4_;
	gint _tmp5_;
	gint _tmp6_;
	gint _tmp7_;
	memset (self, 0, sizeof (Metrics));
	_tmp0_ = bullet;
	(*self).bullet = _tmp0_;
	_tmp1_ = enemy1;
	(*self).enemy1 = _tmp1_;
	_tmp2_ = enemy2;
	(*self).enemy2 = _tmp2_;
	_tmp3_ = enemy3;
	(*self).enemy3 = _tmp3_;
	_tmp4_ = explosion;
	(*self).explosion = _tmp4_;
	_tmp5_ = bang;
	(*self).bang = _tmp5_;
	_tmp6_ = particle;
	(*self).particle = _tmp6_;
	_tmp7_ = count;
	(*self).count = _tmp7_;
}


Metrics* metrics_dup (const Metrics* self) {
	Metrics* dup;
	dup = g_new0 (Metrics, 1);
	memcpy (dup, self, sizeof (Metrics));
	return dup;
}


void metrics_free (Metrics* self) {
	g_free (self);
}


GType metrics_get_type (void) {
	static volatile gsize metrics_type_id__volatile = 0;
	if (g_once_init_enter (&metrics_type_id__volatile)) {
		GType metrics_type_id;
		metrics_type_id = g_boxed_type_register_static ("Metrics", (GBoxedCopyFunc) metrics_dup, (GBoxedFreeFunc) metrics_free);
		g_once_init_leave (&metrics_type_id__volatile, metrics_type_id);
	}
	return metrics_type_id__volatile;
}



