/* main.c generated by valac 0.36.4-dirty, the Vala compiler
 * generated from main.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <SDL2/SDL.h>
#include <SDL2/SDL_ttf.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_mixer.h>
#include <SDL2/SDL_audio.h>
#include <SDL2/SDL_video.h>
#include <SDL2/SDL_render.h>
#include <float.h>
#include <math.h>
#include <SDL2/SDL_keyboard.h>

#define _g_free0(var) (var = (g_free (var), NULL))

#define TYPE_GAME (game_get_type ())
#define GAME(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_GAME, Game))
#define GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_GAME, GameClass))
#define IS_GAME(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_GAME))
#define IS_GAME_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_GAME))
#define GAME_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_GAME, GameClass))

typedef struct _Game Game;
typedef struct _GameClass GameClass;
#define _g_object_unref0(var) ((var == NULL) ? NULL : (var = (g_object_unref (var), NULL)))
#define _SDL_DestroyRenderer0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyRenderer (var), NULL)))
#define _SDL_DestroyWindow0(var) ((var == NULL) ? NULL : (var = (SDL_DestroyWindow (var), NULL)))



gint logSDLError (const gchar* reason);
gint _vala_main (gchar** args, int args_length1);
GType game_get_type (void) G_GNUC_CONST;
Game* game_new (const gchar* title, gint width, gint height, SDL_Window* window, SDL_Renderer* renderer);
Game* game_construct (GType object_type, const gchar* title, gint width, gint height, SDL_Window* window, SDL_Renderer* renderer);
void game_start (Game* self);
gboolean game_get_isRunning (Game* self);
void game_handleEvents (Game* self);
gboolean game_getKey (Game* self, gint key);
void game_stop (Game* self);
void game_refresh (Game* self);
void game_update (Game* self, gdouble delta);
void game_draw (Game* self, gint fps, gdouble avg);


inline gint logSDLError (const gchar* reason) {
	gint result = 0;
	const gchar* _tmp0_;
	gchar* _tmp1_;
	gchar* _tmp2_;
	gchar* _tmp3_;
	gchar* _tmp4_;
	const gchar* _tmp5_;
	gchar* _tmp6_;
	gchar* _tmp7_;
	g_return_val_if_fail (reason != NULL, 0);
	_tmp0_ = reason;
	_tmp1_ = g_strconcat ("Unable to ", _tmp0_, NULL);
	_tmp2_ = _tmp1_;
	_tmp3_ = g_strconcat (_tmp2_, ", SDL error: ", NULL);
	_tmp4_ = _tmp3_;
	_tmp5_ = SDL_GetError ();
	_tmp6_ = g_strconcat (_tmp4_, _tmp5_, NULL);
	_tmp7_ = _tmp6_;
	logSDLError (_tmp7_);
	_g_free0 (_tmp7_);
	_g_free0 (_tmp4_);
	_g_free0 (_tmp2_);
	result = 0;
	return result;
}


gint _vala_main (gchar** args, int args_length1) {
	gint result = 0;
	gchar* title = NULL;
	gchar* _tmp0_;
	gint width = 0;
	gint height = 0;
	gint _tmp1_;
	gint _tmp3_;
	gint _tmp5_;
	gint _tmp7_;
	SDL_Window* window = NULL;
	const gchar* _tmp9_;
	gint _tmp10_;
	gint _tmp11_;
	SDL_Window* _tmp12_;
	SDL_Renderer* renderer = NULL;
	SDL_Window* _tmp13_;
	SDL_Renderer* _tmp14_;
	gdouble delta = 0.0;
	gdouble d = 0.0;
	gint fps = 0;
	gint k = 0;
	gdouble t = 0.0;
	gdouble avg = 0.0;
	gint k2 = 0;
	Game* game = NULL;
	const gchar* _tmp15_;
	gint _tmp16_;
	gint _tmp17_;
	SDL_Window* _tmp18_;
	SDL_Renderer* _tmp19_;
	Game* _tmp20_;
	gdouble mark1 = 0.0;
	gint64 _tmp21_;
	Game* _tmp22_;
	_tmp0_ = g_strdup ("Shmupwarz");
	title = _tmp0_;
	width = 720;
	height = 600;
	_tmp1_ = SDL_Init ((guint32) ((SDL_INIT_VIDEO | SDL_INIT_TIMER) | SDL_INIT_EVENTS));
	if (_tmp1_ < 0) {
		gint _tmp2_;
		_tmp2_ = logSDLError ("initialize SDL");
		result = _tmp2_;
		_g_free0 (title);
		return result;
	}
	_tmp3_ = TTF_Init ();
	if (_tmp3_ < 0) {
		gint _tmp4_;
		_tmp4_ = logSDLError ("initialize TTF fonts");
		result = _tmp4_;
		_g_free0 (title);
		return result;
	}
	_tmp5_ = IMG_Init ((gint) IMG_INIT_PNG);
	if (_tmp5_ < 0) {
		gint _tmp6_;
		_tmp6_ = logSDLError ("initialize PNG images");
		result = _tmp6_;
		_g_free0 (title);
		return result;
	}
	_tmp7_ = Mix_OpenAudio (22050, AUDIO_S16LSB, 2, 4096);
	if (_tmp7_ == -1) {
		gint _tmp8_;
		_tmp8_ = logSDLError ("initialize WAV audio");
		result = _tmp8_;
		_g_free0 (title);
		return result;
	}
	_tmp9_ = title;
	_tmp10_ = width;
	_tmp11_ = height;
	_tmp12_ = SDL_CreateWindow (_tmp9_, (gint) SDL_WINDOWPOS_CENTERED_MASK, (gint) SDL_WINDOWPOS_CENTERED_MASK, _tmp10_, _tmp11_, (guint32) SDL_WINDOW_SHOWN);
	window = _tmp12_;
	_tmp13_ = window;
	_tmp14_ = SDL_CreateRenderer (_tmp13_, -1, (guint32) (SDL_RENDERER_ACCELERATED | SDL_RENDERER_PRESENTVSYNC));
	renderer = _tmp14_;
	delta = 0.0;
	d = 0.0;
	fps = 60;
	k = 0;
	t = 0.0;
	avg = 0.0;
	k2 = 0;
	_tmp15_ = title;
	_tmp16_ = width;
	_tmp17_ = height;
	_tmp18_ = window;
	_tmp19_ = renderer;
	_tmp20_ = game_new (_tmp15_, _tmp16_, _tmp17_, _tmp18_, _tmp19_);
	game = _tmp20_;
	_tmp21_ = g_get_real_time ();
	mark1 = ((gdouble) _tmp21_) / 1000000.0;
	_tmp22_ = game;
	game_start (_tmp22_);
	while (TRUE) {
		Game* _tmp23_;
		gboolean _tmp24_;
		gboolean _tmp25_;
		gdouble mark2 = 0.0;
		gint64 _tmp26_;
		gdouble _tmp27_;
		gdouble _tmp28_;
		gdouble _tmp29_;
		gint _tmp30_;
		gdouble _tmp31_;
		gdouble _tmp32_;
		gdouble _tmp33_;
		Game* _tmp35_;
		Game* _tmp36_;
		gboolean _tmp37_;
		Game* _tmp39_;
		gdouble m1 = 0.0;
		gint64 _tmp40_;
		Game* _tmp41_;
		gdouble _tmp42_;
		gdouble m2 = 0.0;
		gint64 _tmp43_;
		gint _tmp44_;
		gdouble _tmp45_;
		gdouble _tmp46_;
		gdouble _tmp47_;
		gint _tmp48_;
		Game* _tmp51_;
		gint _tmp52_;
		gdouble _tmp53_;
		_tmp23_ = game;
		_tmp24_ = game_get_isRunning (_tmp23_);
		_tmp25_ = _tmp24_;
		if (!_tmp25_) {
			break;
		}
		_tmp26_ = g_get_real_time ();
		mark2 = ((gdouble) _tmp26_) / 1000000.0;
		_tmp27_ = mark2;
		_tmp28_ = mark1;
		delta = _tmp27_ - _tmp28_;
		_tmp29_ = mark2;
		mark1 = _tmp29_;
		_tmp30_ = k;
		k = _tmp30_ + 1;
		_tmp31_ = d;
		_tmp32_ = delta;
		d = _tmp31_ + _tmp32_;
		_tmp33_ = d;
		if (_tmp33_ >= 1.0) {
			gint _tmp34_;
			_tmp34_ = k;
			fps = _tmp34_;
			k = 0;
			d = (gdouble) 0;
		}
		_tmp35_ = game;
		game_handleEvents (_tmp35_);
		_tmp36_ = game;
		_tmp37_ = game_getKey (_tmp36_, (gint) SDLK_ESCAPE);
		if (_tmp37_) {
			Game* _tmp38_;
			_tmp38_ = game;
			game_stop (_tmp38_);
		}
		_tmp39_ = game;
		game_refresh (_tmp39_);
		_tmp40_ = g_get_real_time ();
		m1 = ((gdouble) _tmp40_) / 1000000.0;
		_tmp41_ = game;
		_tmp42_ = delta;
		game_update (_tmp41_, _tmp42_);
		_tmp43_ = g_get_real_time ();
		m2 = ((gdouble) _tmp43_) / 1000000.0;
		_tmp44_ = k2;
		k2 = _tmp44_ + 1;
		_tmp45_ = t;
		_tmp46_ = m2;
		_tmp47_ = m1;
		t = _tmp45_ + (_tmp46_ - _tmp47_);
		_tmp48_ = k2;
		if (_tmp48_ >= 1000) {
			gdouble _tmp49_;
			gdouble _tmp50_;
			_tmp49_ = t;
			avg = _tmp49_ / 1000;
			_tmp50_ = avg;
			g_print ("%f\n", _tmp50_);
			k2 = 0;
			t = 0.0;
		}
		_tmp51_ = game;
		_tmp52_ = fps;
		_tmp53_ = avg;
		game_draw (_tmp51_, _tmp52_, _tmp53_);
	}
	result = 0;
	_g_object_unref0 (game);
	_SDL_DestroyRenderer0 (renderer);
	_SDL_DestroyWindow0 (window);
	_g_free0 (title);
	return result;
}


int main (int argc, char ** argv) {
#if !GLIB_CHECK_VERSION (2,35,0)
	g_type_init ();
#endif
	return _vala_main (argv, argc);
}



